Fixing schema.sql
indiah444/Media-Polarisation-Project pull request #44
Opened 2024-10-08 15:58 UTC by indiah444

- Changed the double quotes used around the seed data to single quotes in line with SQL constraints.
- Updated the order of `DROP TABLE IF EXISTS` commands to make sure tables were dropped in correct order.

2024-10-08 16:13 UTC, YakMan101 requested changes
I think each table should have constraints according the the combination of columns that should be unique. 
e.g for `article` table, maybe not have `article_title` as unique but have combination of:
`(article_title, source_id, date_published)` 
as a unique. incase two different articles happen to have the same title.

2024-10-08 16:13 UTC, YakMan101 commented on database/schema.sql
> +DROP TABLE IF EXISTS article_topic_assignment;
Good reordering to avoid error related to foreign keys

2024-10-09 08:18 UTC, megansam5 requested changes

2024-10-09 08:18 UTC, megansam5 commented on database/schema.sql
>      polarity_score FLOAT NOT NULL,
sorry to be annoying, but I think we are now also keeping article_content (probably text as it may be large)

2024-10-09 08:40 UTC, YakMan101 approved these changes

2024-10-09 08:45 UTC, megansam5 approved these changes
All looks good!

2024-10-09 08:45 UTC, megansam5 commented on database/schema.sql
> +    article_content TEXT NOT NULL,
Thank you for adding the content!

2024-10-09 08:46 UTC, merged